apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - online_shop_deployment.yml # Exact match hona chahiye
  - online_shop_svc.yml
images:
  - name: muhammadali792/online_shop
    newTag: v1.0.6
