# image-updater/chai-app/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# list the manifest files in this directory
resources:
  - deployment.yml
  - service.yml
images:
  - name: muhammadali792/chai-devops
    newTag: v1.0.1
